# Generated by Django 4.2 on 2023-04-15 20:45

from django.db import migrations, models
import petstagram.main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_pet_user_profile_alter_pet_name_alter_pet_pets_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[petstagram.main_app.validators.validate_max_size])),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('tagged_pets', models.ManyToManyField(to='main_app.pet')),
            ],
        ),
    ]
